version: "3.7"
 
services:
 
  cassandra-1:
    image: "cassandra:3.11.9"
    container_name: "cassandra-1"
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"
 
  cassandra-2:
    image: "cassandra:3.11.9"
    container_name: "cassandra-2"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"
    depends_on:
      - "cassandra-1"
 
  cassandra-3:
    image: "cassandra:3.11.9"
    container_name: "cassandra-3"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"
    depends_on:
      - "cassandra-2"
